version: '3'
services:
  debunker-api:
    container_name: debunker-api
    environment:
      - RAILS_ENV=development
    restart: always
    build:
      dockerfile: Dockerfile
    ports:
     - '3001:3001'
    volumes:
      - .:/debunker-api
    depends_on:
      - database
      - redis

  database:
    container_name: debunker-api-database
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - database:/var/lib/postgresql/data

  redis:
    container_name: debunker-api-redis
    image: redis

volumes:
  database:
